player_stats = {
    "hp": 80,
    "mp": 50,
    "energia": 70,
    "exp": 40,
    "lokalizacja": "Las",
    "attributes": {
        "Siła": 10,
        "Zręczność": 12,
        "Inteligencja": 14,
        "Mądrość": 11,
        "Charyzma": 13,
        "Intuicja": 8,
        "Zielarstwo": 5,
        "Oswajanie": 6,
        "Oszustwo": 4,
        "Percepcja": 7,
        "Perswazja": 10,
        "Przyroda": 6,
        "Wiara": 5,
        "Skradanie": 8,
        "Surwiwal": 9,
        "Śledztwo": 7,
        "Zastraszanie": 3,
        "Kradzież": 4,
        "Crafting": 6,
        "Gotowanie": 5,
    },
    "dzien": 1,
    "godzina": 12,
    # 🔹 maksymalne wartości
    "hp_max": 100,
    "mp_max": 100,
    "energia_max": 100,
    "exp_max": 100  # <- dodajemy też EXP max
}
